export enum IconEnum {
  html = 'Html5',
  next = 'Nextjs',
  sass = 'Sass',
  angular = 'Angular',
  react = 'React',
  typescript = 'Typescript',
  git = 'Git',
  redux = 'Redux',
  node = 'Nodejs',
  mongo = 'Mongodb',
  mysql = 'Mysql',
  code = 'Code',
  briefCase = 'Briefcase',
  translate = 'Language',
  linkedin = 'Linkedin',
  github = 'GithubFilled',
  whatsApp = 'Whatsapp',
  download = 'FileDownload'
}
